version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: scripts/clean_up.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
